[tasks.openapi-delete]
cwd = "openapi"
command = "rm"
args = ["-f", "spec3.json"]

[tasks.openapi-fetch]
cwd = "openapi"
command = "wget"
args = [
    "https://raw.githubusercontent.com/stripe/openapi/master/openapi/spec3.json",
]
dependencies = ["openapi-delete"]

[tasks.openapi-generate]
cwd = "openapi"
command = "cargo"
args = ["run", "spec3.json"]
dependencies = ["openapi-fetch"]

[tasks.openapi-copy]
cwd = "openapi"
command = "cp"
args = ["-a", "out/.", "../src/resources/generated"]
dependencies = ["openapi-generate"]

[tasks.fmt]
env = { RUST_FILES = { glob = "./**/*.rs", include_files = true, include_dirs = false, ignore_type = "git" } }
command = "cargo"
toolchain = "nightly"
install_crate = "rustfmt"
args = ["fmt", "--", "@@split(RUST_FILES,;)"]

[tasks.openapi-install]
dependencies = ["openapi-copy", "fmt"]

[config]
default_to_workspace = false
